name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [win-x64]
        include:
          - target: win-x64
            platform: win
            architecture: x64
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: "8.0.x"

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2.0.0

      - name: Build CLI utilities
        shell: pwsh
        run: |
          msbuild /m /t:restore,resignbsp:publish /p:Platform=${{ matrix.architecture }} /p:RuntimeIdentifier=${{ matrix.platform }}-${{ matrix.architecture }} /p:PublishDir=${{ github.workspace }}/artifacts/${{ matrix.platform }}-${{ matrix.architecture }}/CLIs /p:PublishSingleFile=true /p:PublishTrimmed=true /p:Configuration=Release /p:IncludeNativeLibrariesForSelfExtract=true ResignBSP.sln

      - name: Create PDB Output Directory
        shell: pwsh
        run: |
          mkdir ${{ github.workspace }}\artifacts\${{ matrix.platform }}-${{ matrix.architecture }}\PDBs

      - name: Move PDBs
        shell: pwsh
        run: |
          move ${{ github.workspace }}\artifacts\${{ matrix.platform }}-${{ matrix.architecture }}\CLIs\*.pdb ${{ github.workspace }}\artifacts\${{ matrix.platform }}-${{ matrix.architecture }}\PDBs\

      - name: Upload artifact (Binaries)
        uses: actions/upload-artifact@v4.0.0
        with:
          name: ${{ matrix.platform }}-${{ matrix.architecture }}-binaries
          path: ${{ github.workspace }}/artifacts/${{ matrix.platform }}-${{ matrix.architecture }}\CLIs

      - name: Upload artifact (Symbols)
        uses: actions/upload-artifact@v4.0.0
        with:
          name: ${{ matrix.platform }}-${{ matrix.architecture }}-symbols
          path: ${{ github.workspace }}/artifacts/${{ matrix.platform }}-${{ matrix.architecture }}\PDBs